name = "pro"
main = ".open-next/worker.js"
compatibility_date = "2026-06-17"
account_id = "27323dd4a4906aeec2b9192f9ccdb634"

workers_dev = true
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run cloudflare:build"